vich_uploader:
    db_driver: orm

    mappings:
        stuff_illustration:
            uri_prefix: /images/stuff_illustrations
            upload_destination: '%kernel.project_dir%/public/images/stuff_illustrations'
            namer: Vich\UploaderBundle\Naming\Base64Namer
            delete_on_remove: true
            delete_on_update: true
